modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="quill"
version="1.1.0"
displayName="Salju's Quill"
credits="Jusey1"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
authors="Jusey1"
description="Small collection of edits"

[[dependencies.quill]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




